power: bq2589x_chg_mmi: Fix implicit-int error
drivers/power/bq2589x_chg_mmi/bq2589x_charger.c:1518:8: error: type
specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
static bq2589x_reuqest_dpdm(struct bq2589x *bq, bool enable)
~~~~~~ ^
int
1 error generated.

Change-Id: I05d81da96a672ac64a5ba13718339d50ad3c9899
Signed-off-by: Sevenrock <sevenrock@hotmail.de>